name: FactoryMod
main: com.github.igotyou.FactoryMod.FactoryMod
author: Maxopoly, igotyou
version: 2.7.0-SNAPSHOT
depend: [CivModCore]
softdepend: [CivMenu, NameLayer, Citadel]
permissions:
    fm.public:
        default: true
    fm.op:
        default: op
api-version: 1.17
